In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import norm
import os
from scipy.stats import zscore
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.multitest import fdrcorrection
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from IPython.display import clear_output

## SysBio Blood Transcriptomics Sample Harmonization and PCA Plot Creation
### Harmonizing Blood Transcriptomics from AMP PD and AMP CMD

In [ ]:
# Paths to SysBio blood AMP PD and AMP CMD transcriptomics datasets
CMD_df = pd.read_csv("sysbio/Transcriptomics/Blood/CMD/GSE118165_raw_counts_GRCh38.p13_NCBI 2.tsv", sep = "\t", engine='c')
PD_df= pd.read_csv("sysbio/Transcriptomics/Blood/PD/releases_2023_v4release_1027_rnaseq-WB-RWTS-VHBS_subread_feature-counts_matrix.featureCounts.tsv", sep = "\t", engine='c')
cmd_samples = pd.read_csv("sysbio/Transcriptomics/Blood/CMD/Sample_Data.csv", engine='c')
cmd_gene_Ann = pd.read_csv("sysbio/Transcriptomics/Blood/CMD/Human.GRCh38.p13.annot 2.tsv", sep = "\t", engine='c')

In [ ]:
# View AMP PD dataset
PD_df

In [ ]:
# Rename samples
id_to_name = dict(zip(cmd_samples['Sample_ID'], cmd_samples['Sample_Name']))
CMD_df = CMD_df.rename(columns=id_to_name)
print(CMD_df.head())

      GeneID  1001-Bulk_B-U  1001-Bulk_B-S  1001-Mem_B-U  1001-Mem_B-S  \
0  100287102              5              1             3             1
1     653635            433            167           307           210
2  102466751              7              3             3             1
3  107985730              0              0             2             0
4  100302278              0              0             0             0

   1001-Naive_B-U  1001-Naive_B-S  1001-Plasmablasts-U  1001-CD8pos_T-U  \
0               0               0                    0                1
1             474             243                   47              362
2               0               0                    0                2
3               0               0                    0                0
4               0               0                    0                0

   1001-CD8pos_T-S  ...  GSM3319899  GSM3319900  GSM3319901  GSM3319902  \
0               24  ...           1           2           2           0
1              381  ...         139          84          53          71
2                4  ...           0           0           0           0
3                2  ...           0           0           2           1
4                0  ...           0           0           0           0

   GSM3319903  GSM3319904  GSM3319905  GSM3319906  GSM3319907  GSM3319908
0          22          12           7          14           0           0
1          70          28          14          37          71          34
2           2           2           1           1           0           0
3           0           6           1           4           0           0
4           0           2           0           1           0           0

[5 rows x 166 columns]

In [ ]:
# Merge AMP CMD samples with gene annotation datasets
CMD_df = pd.merge(CMD_df, cmd_gene_Ann[['GeneID', 'Symbol']], on='GeneID', how='left')
CMD_df = CMD_df.set_index('Symbol')
CMD_df = CMD_df.drop('GeneID', axis=1)

In [ ]:
# Verify this was done correctly
CMD_df.head()

In [ ]:
# Remove version numbers from Geneid
PD_df["EnsemblGeneID"] = PD_df["Geneid"].str.split(".").str[0]  # Rename here

# Ensure GeneID is a string in both DataFrames
PD_df["EnsemblGeneID"] = PD_df["EnsemblGeneID"].astype(str)
cmd_gene_Ann["EnsemblGeneID"] = cmd_gene_Ann["EnsemblGeneID"].astype(str)

# Perform the merge
PD_df = pd.merge(PD_df, cmd_gene_Ann[['EnsemblGeneID', 'Symbol']], on='EnsemblGeneID', how='left')

# Set index to Symbol and drop GeneID
# df_pd = df_pd.rename(columns={'_id': 'Geneid'})
# PD_df = PD_df.merge(cmd_gene_Ann, on='Geneid', how='left')

In [ ]:
# Drop Geneid column from the AMP PD dataset and view
# PD_df = PD_df.set_index('Symbol', drop=True)
PD_df = PD_df.drop(columns=["Geneid"])
PD_df.head(500)

In [ ]:
# Check dimensions
print("Dataset 1 shape:", df1.shape)
print("Dataset 2 shape:", df2.shape)

In [ ]:
# Get intersection of common genes between the datasets
common_genes = df1.index.intersection(df2.index)

# Subset both datasets to common genes
df1 = df1.loc[common_genes]
df2 = df2.loc[common_genes]

In [ ]:
# Concatenate and get shape of the full dataset
merged_counts = pd.concat([df1, df2], axis=1)
print("Merged dataset shape:", merged_counts.shape)

In [ ]:
# Read AMP PD metadata
PD_metadata = pd.read_csv("sysbio/Transcriptomics/Blood/PD/releases_2023_v4release_1027_amp_pd_case_control.csv")

,participant_id,diagnosis_at_baseline,diagnosis_latest,case_control_other_at_baseline,case_control_other_latest
0,BF-1001,No PD Nor Other Neurological Disorder,No PD Nor Other Neurological Disorder,Control,Control
1,BF-1002,Idiopathic PD,Idiopathic PD,Case,Case
2,BF-1003,Idiopathic PD,Idiopathic PD,Case,Case
3,BF-1004,Idiopathic PD,Idiopathic PD,Case,Case
4,BF-1005,No PD Nor Other Neurological Disorder,No PD Nor Other Neurological Disorder,Control,Control

In [ ]:
# Subset AMP PD metadata to needed columns
PD_metadata = PD_metadata[["participant_id", "case_control_other_at_baseline"]]

pd_columns = list(PD_df.columns)

  participant_id case_control_other_at_baseline
0        BF-1001                        Control
1        BF-1002                           Case
2        BF-1003                           Case
3        BF-1004                           Case
4        BF-1005                        Control

In [ ]:
# Process strings to get needed samples
processed_strings = ["-".join(s.split("-")[:2]) for s in pd_columns]
print(processed_strings)

['HB-PD_INVXJ837TXN', 'HB-PD_INVPM710NJH', 'HB-PD_INVZC874MMT', 'HB-PD_INVWV624HAC', 'HB-PD_INVPK123UPD', 'HB-PD_INVHH968RZZ', 'HB-PD_INVWX362DL7', 'HB-PD_INVMW322DFP', 'HB-PD_INVCT548DEW', 'HB-PD_INVUL535YVX', 'HB-PD_INVAV201WYD', 'HB-PD_INVKM762GER', 'HB-PD_INVJF352UPG', 'HB-PD_INVCT548DEW', 'HB-PD_INVDG518AMF', 'HB-PD_INVAN423JWN', 'HB-PD_INVMG411AZK', 'HB-PD_INVRV224UAG', 'HB-PD_INVXD751CUN', 'HB-PD_INVCN268UPG', 'HB-PD_INVYZ403ABE', 'HB-PD_INVPE171ERM', 'HB-PD_INVZF591WW3', 'HB-PD_INVTE998TK0', 'HB-PD_INVTK579XW5', 'HB-PD_INVXC273EFP', 'HB-PD_INVFL000FBG', 'HB-PD_INVMY952TRF', 'HB-PD_INVDY491VZH', 'HB-PD_INVGV809WE0', 'HB-PD_INVLM077KED', 'HB-PD_INVVY168ZP9', 'HB-PD_INVWX925JX3', 'HB-PD_INVYK689VP7', 'HB-PD_INVBB462PV9', 'HB-PD_INVZA054JF4', 'HB-PD_INVRD245ZDR', 'HB-PD_INVXH634NAU', 'HB-PD_INVGW929KM2', 'HB-PD_INVUD383EXF', 'HB-PD_INVLL564YGH', 'HB-PD_INVTA736CUG', 'HB-PD_INVNU085CP9', 'HB-PD_INVYA693JP9', 'HB-PD_INVKN359MYE', 'HB-PD_INVRZ126CZ1', 'HB-PD_INVPJ782GYM', 'HB-PD_INVHX423RRQ', 'HB-PD_INVDL979RRB', 'HB-PD_INVVF912FXN', 'HB-PD_INVDX373MWV', 'HB-PD_INVLW842XHX', 'HB-PD_INVVZ973LRV', 'HB-PD_INVXW921GG8', 'HB-PD_INVPJ612ZL0', 'HB-PD_INVEM226TCU', 'HB-PD_INVZD105WP0', 'HB-PD_INVRV248MXJ', 'HB-PD_INVUJ813CTX', 'HB-PD_INVEY788YLQ', 'HB-PD_INVVD953YJZ', 'HB-PD_INVWC787PBU', 'HB-PD_INVWD107WV0', 'HB-PD_INVEA914BYC', 'HB-PD_INVLR050HV9', 'HB-PD_INVPG781HYV', 'HB-PD_INVGP996TTC', 'HB-PD_INVCW367VWE', 'HB-PD_INVTE300LC8', 'HB-PD_INVBW847XWJ', 'HB-PD_INVAY982GGL', 'HB-PD_INVGD551KWU', 'HB-PD_INVDP245UPF', 'HB-PD_INVKN359MYE', 'HB-PD_INVMP221NA4', 'HB-PD_INVMD766FB7', 'HB-PD_INVUF542CRR', 'HB-PD_INVYM520ZRY', 'HB-PD_INVTY501LVC', 'HB-PD_INVMT562GR7', 'HB-PD_INVXB837HK7', 'HB-PD_INVPH382RXC', 'HB-PD_INVFA695WR8', 'HB-PD_INVXG469LU7', 'HB-PD_INVMA476BGX', 'HB-PD_INVYW786VUD', 'HB-PD_INVKL192GW7', 'HB-PD_INVJJ715WZM', 'HB-PD_INVGV809WE0', 'HB-PD_INVBN609PXB', 'HB-PD_INVFL000FBG', 'HB-PD_INVVH170PRJ', 'HB-PD_INVAR992XUZ', 'HB-PD_INVHM609MG8', 'HB-PD_INVNU270PWY', 'HB-PD_INVBD604UJD', 'HB-PD_INVCE243DNF', 'HB-PD_INVFW182RFT', 'HB-PD_INVDV220XUE', 'HB-PD_INVCA659FVZ', 'HB-PD_INVJP816BLF', 'HB-PD_INVLT157BZD', 'HB-PD_INVEF708KCH', 'HB-PD_INVZR347JWY', 'HB-PD_INVCE617KZX', 'HB-PD_INVRE473WBY', 'HB-PD_INVUC592KBE', 'HB-PD_INVCL303MWF', 'HB-PD_INVZH922GXN', 'HB-PD_INVNY929FWN', 'HB-PD_INVGZ624NYL', 'HB-PD_INVEZ002CMD', 'HB-PD_INVBA295LGX', 'HB-PD_INVVW052EBJ', 'HB-PD_INVHX788VYX', 'HB-PD_INVRE591WEJ', 'HB-PD_INVEW270XJK', 'HB-PD_INVUJ512TJL', 'HB-PD_INVHH968RZZ', 'HB-PD_INVHZ559VAV', 'HB-PD_INVEG293CYZ', 'HB-PD_INVCX130BPY', 'HB-PD_INVTE300LC8', 'HB-PD_INVAN471HLU', 'HB-PD_INVKL811ZLY', 'HB-PD_INVRM070GNC', 'HB-PD_INVFK553TXD', 'HB-PD_INVHX423RRQ', 'HB-PD_INVJZ026ZJQ', 'HB-PD_INVFZ299DJD', 'HB-PD_INVDX722LZJ', 'HB-PD_INVEJ258NFN', 'HB-PD_INVWM460URW', 'HB-PD_INVZU482RVG', 'HB-PD_INVXC273EFP', 'HB-PD_INVHZ876NN4', 'HB-PD_INVNG182JFL', 'HB-PD_INVJB923BMW', 'HB-PD_INVJY618EVJ', 'HB-PD_INVBV727RB0', 'HB-PD_INVRT078KR7', 'HB-PD_INVZA171VKV', 'HB-PD_INVXV506KHV', 'HB-PD_INVEP343XWP', 'HB-PD_INVAN423JWN', 'HB-PD_INVKP207BY2', 'HB-PD_INVRC954HCG', 'HB-PD_INVEW270XJK', 'HB-PD_INVLM916AK6', 'HB-PD_INVDY797MD3', 'HB-PD_INVVB692RKE', 'HB-PD_INVYU123HL5', 'HB-PD_INVRP927JCT', 'HB-PD_INVFP955BLX', 'HB-PD_INVYH256XZD', 'HB-PD_INVEM279BGJ', 'HB-PD_INVKJ120VLF', 'HB-PD_INVZX511PA8', 'HB-PD_INVBB508ETG', 'HB-PD_INVYN878DRU', 'HB-PD_INVWL491VHT', 'HB-PD_INVNJ509XCP', 'HB-PD_INVGA953JR3', 'HB-PD_INVNU470WLG', 'HB-PD_INVRV248MXJ', 'HB-PD_INVAT768TZD', 'HB-PD_INVPN172RF8', 'HB-PD_INVDA909JVK', 'HB-PD_INVXH634NAU', 'HB-PD_INVDP245UPF', 'HB-PD_INVMV147MDY', 'HB-PD_INVNF986PDX', 'HB-PD_INVEK041HFQ', 'HB-PD_INVMG477KEB', 'HB-PD_INVEU686NEC', 'HB-PD_INVEP238WM5', 'HB-PD_INVVP040FPF', 'HB-PD_INVLH714CDC', 'HB-PD_INVWC537DZP', 'HB-PD_INVZP355HUF', 'HB-PD_INVPR426NZE', 'HB-PD_INVAF194FCZ', 'HB-PD_INVVW882NNL', 'HB-PD_INVVY910XCA', 'HB-PD_INVDR834KT6', 'HB-PD_INVLG477VFJ', 'HB-PD_INVKM762GER', 'HB-PD_INVVD490MY8', 'HB-PD_INVHA351TZA', 'HB-PD_INVVB976YMT', 'HB-PD_INVJL623KZJ', 'HB-PD_INVXZ479VFP', 'HB-PD_INVHY628ZET', 'HB-PD_INVVG233ZUC', 'HB-PD_INVKT483DW1', 'HB-PD_INVLL761LUR', 'HB-PD_INVWU757PGL', 'HB-PD_INVFV309PGF', 'HB-PD_INVBX181DJ7', 'HB-PD_INVRC954HCG', 'HB-PD_INVFZ601AVR', 'HB-PD_INVFA695WR8', 'HB-PD_INVNJ974GT9', 'HB-PD_INVHX788VYX', 'HB-PD_INVFK553TXD', 'HB-PD_INVRM142PGU', 'HB-PD_INVNA827AC2', 'HB-PD_INVGG854VFB', 'HB-PD_INVKC407HM3', 'HB-PD_INVAG118ZY3', 'HB-PD_INVWD866VYY', 'HB-PD_INVKT171FZQ', 'HB-PD_INVRT854TUP', 'HB-PD_INVTU721FXU', 'HB-PD_INVJR775CAD', 'HB-PD_INVEZ002CMD', 'HB-PD_INVCE617KZX', 'HB-PD_INVYP127KH7', 'HB-PD_INVFW763FLM', 'HB-PD_INVPY386EZ1', 'HB-PD_INVBL785HCR', 'HB-PD_INVTN280KK2', 'HB-PD_INVET132LKT', 'HB-PD_INVHJ410LUY', 'HB-PD_INVMJ225EDX', 'HB-PD_INVVZ171WMC', 'HB-PD_INVUY723HWK', 'HB-PD_INVTG837KDT', 'HB-PD_INVKN359MYE', 'HB-PD_INVBJ734PKG', 'HB-PD_INVNB363VHH', 'HB-PD_INVKL192GW7', 'HB-PD_INVVZ810CL4', 'HB-PD_INVMY889XPG', 'HB-PD_INVDG518AMF', 'HB-PD_INVXW747AZ4', 'HB-PD_INVZF030ANB', 'HB-PD_INVEZ703XCT', 'HB-PD_INVKB855MNC', 'HB-PD_INVMW322DFP', 'HB-PD_INVZY899BLD', 'HB-PD_INVGD551KWU', 'HB-PD_INVFV290FVM', 'HB-PD_INVDC903NK0', 'HB-PD_INVYH256XZD', 'HB-PD_INVEJ662KV5', 'HB-PD_INVRH572AT6', 'HB-PD_INVXR188WBE', 'HB-PD_INVRJ565ENK', 'HB-PD_INVBW207YCU', 'HB-PD_INVKL096GBK', 'HB-PD_INVNG393RCA', 'HB-PD_INVZP355HUF', 'HB-PD_INVBD604UJD', 'HB-PD_INVLG477VFJ', 'HB-PD_INVEG496BFK', 'HB-PD_INVYH703GTY', 'HB-PD_INVYC255CTZ', 'HB-PD_INVVL940TMQ', 'HB-PD_INVFY710TUL', 'HB-PD_INVYE811LLA', 'HB-PD_INVNU470WLG', 'HB-PD_INVME855WDK', 'HB-PD_INVZC389ZW4', 'HB-PD_INVUC080EAV', 'HB-PD_INVFP955BLX', 'HB-PD_INVJY618EVJ', 'HB-PD_INVWD831MJN', 'HB-PD_INVNU223XZ6', 'HB-PD_INVZX511PA8', 'HB-PD_INVJH291ACA', 'HB-PD_INVPF517DTL', 'HB-PD_INVXW921GG8', 'HB-PD_INVVR402VTL', 'HB-PD_INVPJ782GYM', 'HB-PD_INVVD490MY8', 'HB-PD_INVUZ798EBX', 'HB-PD_INVKU843MGU', 'HB-PD_INVAE296YP8', 'HB-PD_INVML326LKX', 'HB-PD_INVXP571YY7', 'HB-PD_INVYU123HL5', 'HB-PD_INVKT966MN3', 'HB-PD_INVWJ779MM6', 'HB-PD_INVGP631BHZ', 'HB-PD_INVLT278CV0', 'HB-PD_INVWP863XGT', 'HB-PD_INVFW188ULK', 'HB-PD_INVLN081LWQ', 'HB-PD_INVCZ382ZKF', 'HB-PD_INVFB954CZL', 'HB-PD_INVWU757PGL', 'HB-PD_INVCF880VPM', 'HB-PD_INVXB431DEK', 'HB-PD_INVFG251LYU', 'HB-PD_INVRU910TJM', 'HB-PD_INVRH775AP0', 'HB-PD_INVDM231AMK', 'HB-PD_INVWC268DZQ', 'HB-PD_INVHX359JA4', 'HB-PD_INVKJ945YXX', 'HB-PD_INVXV506KHV', 'HB-PD_INVBZ116NBF', 'HB-PD_INVZG343ZG1', 'HB-PD_INVLZ949CU1', 'HB-PD_INVEK775PZ1', 'HB-PD_INVRB746NDP', 'HB-PD_INVGV809WE0', 'HB-PD_INVUC080EAV', 'HB-PD_INVFX634PTH', 'HB-PD_INVHY628ZET', 'HB-PD_INVFG174KZN', 'HB-PD_INVVY168ZP9', 'HB-PD_INVMY698YC7', 'HB-PD_INVXB837HK7', 'HB-PD_INVUC080EAV', 'HB-PD_INVFK806NX7', 'HB-PD_INVUL535YVX', 'HB-PD_INVXW804UWZ', 'HB-PD_INVJR904CK1', 'HB-PD_INVRU892YEU', 'HB-PD_INVTA736CUG', 'HB-PD_INVVX051CP7', 'HB-PD_INVZF970DV4', 'HB-PD_INVGP996TTC', 'HB-PD_INVMR748YFJ', 'HB-PD_INVRE473WBY', 'HB-PD_INVHV564VEL', 'HB-PD_INVCM666MMW', 'HB-PD_INVBP774LAT', 'HB-PD_INVAF323PK0', 'HB-PD_INVKJ120VLF', 'HB-PD_INVUB834JNH', 'HB-PD_INVJT536LM4', 'HB-PD_INVCY834XNR', 'HB-PD_INVVY910XCA', 'HB-PD_INVEG707KZK', 'HB-PD_INVVZ810CL4', 'HB-PD_INVWF089YN8', 'HB-PD_INVVR593ATF', 'HB-PD_INVDG433RE5', 'HB-PD_INVFW763FLM', 'HB-PD_INVFN943GGX', 'HB-PD_INVPM710NJH', 'HB-PD_INVMY779EYE', 'HB-PD_INVCY777XPX', 'HB-PD_INVBT723CD0', 'HB-PD_INVHH968RZZ', 'HB-PD_INVFP947RHZ', 'HB-PD_INVBA872AKX', 'HB-PD_INVAJ225ZAN', 'HB-PD_INVBY834PUY', 'HB-PD_INVPH382RXC', 'HB-PD_INVME983PVW', 'HB-PD_INVZC389ZW4', 'HB-PD_INVWH173JX6', 'HB-PD_INVJX788XTB', 'HB-PD_INVNU085CP9', 'HB-PD_INVWD107WV0', 'HB-PD_INVNT332YE3', 'HB-PD_INVUX799ZYN', 'HB-PD_INVEU611PUN', 'HB-PD_INVYH703GTY', 'HB-PD_INVYC255CTZ', 'HB-PD_INVVG290KEJ', 'HB-PD_INVVH170PRJ', 'HB-PD_INVKB560VKQ', 'HB-PD_INVHE822LK3', 'HB-PD_INVNZ757REY', 'HB-PD_INVAB465GYE', 'HB-PD_INVXU574AG4', 'HB-PD_INVZL198WEA', 'HB-PD_INVRF972FVE', 'HB-PD_INVBL785HCR', 'HB-PD_INVPK256ZYD', 'HB-PD_INVUZ798EBX', 'HB-PD_INVJE288HXW', 'HB-PD_INVLJ120YP8', 'HB-PD_INVLG477VFJ', 'HB-PD_INVAH321FNC', 'HB-PD_INVHA351TZA', 'HB-PD_INVBZ116NBF', 'HB-PD_INVJK763PMP', 'HB-PD_INVKH838FRA', 'HB-PD_INVLH617NTN', 'HB-PD_INVCV796VDY', 'HB-PD_INVWP863XGT', 'HB-PD_INVAV201WYD', 'HB-PD_INVJB923BMW', 'HB-PD_INVED353HFW', 'HB-PD_INVWP309GFP', 'HB-PD_INVLN081LWQ', 'HB-PD_INVYE813FJ7', 'HB-PD_INVEK775PZ1', 'HB-PD_INVDK184UA1', 'HB-PD_INVNG182JFL', 'HB-PD_INVFP716LL3', 'HB-PD_INVCT956UPT', 'HB-PD_INVKJ945YXX', 'HB-PD_INVDX722LZJ', 'HB-PD_INVHZ876NN4', 'HB-PD_INVEP261UL8', 'HB-PD_INVZY899BLD', 'HB-PD_INVJH499PC5', 'HB-PD_INVEG707KZK', 'HB-PD_INVTW374WGZ', 'HB-PD_INVGM472XLN', 'HB-PD_INVAT813UH6', 'HB-PD_INVHR490LEK', 'HB-PD_INVCY121MD0', 'HB-PD_INVEG130RU6', 'HB-PD_INVWD831MJN', 'HB-PD_INVVW882NNL', 'HB-PD_INVXW592YL6', 'HB-PD_INVGP177VUR', 'HB-PD_INVDA056MAY', 'HB-PD_INVZG343ZG1', 'HB-PD_INVRH775AP0', 'HB-PD_INVWF044ZN0', 'HB-PD_INVWK541DA1', 'HB-PD_INVRR113RA3', 'HB-PD_INVYG352RAT', 'HB-PD_INVKT210TKP', 'HB-PD_INVFG174KZN', 'HB-PD_INVWW508UTT', 'HB-PD_INVPW750EM0', 'HB-PD_INVKB552KRA', 'HB-PD_INVWK621GKJ', 'HB-PD_INVXP571YY7', 'HB-PD_INVDY625CF3', 'HB-PD_INVVE075GJH', 'HB-PD_INVNF986PDX', 'HB-PD_INVNU697YE1', 'HB-PD_INVVR134MMF', 'HB-PD_INVFY875JK3', 'HB-PD_INVWJ650ZFE', 'HB-PD_INVJR904CK1', 'HB-PD_INVPP770LPG', 'HB-PD_INVAJ225ZAN', 'HB-PD_INVLW344MP2', 'HB-PD_INVYG652XNP', 'HB-PD_INVHH297BET', 'HB-PD_INVBL776UJE', 'HB-PD_INVME726DNW', 'HB-PD_INVUY723HWK', 'HB-PD_INVLH714CDC', 'HB-PD_INVYJ017AHX', 'HB-PD_INVKM762GER', 'HB-PD_INVKB727VWA', 'HB-PD_INVWZ859GWD', 'HB-PD_INVVG290KEJ', 'HB-PD_INVAT813UH6', 'HB-PD_INVLU716LVE', 'HB-PD_INVGN484CJW', 'HB-PD_INVUP391RFE', 'HB-PD_INVNZ565VEK', 'HB-PD_INVGW890FG8', 'HB-PD_INVCA659FVZ', 'HB-PD_INVLN063PU6', 'HB-PD_INVBL776UJE', 'HB-PD_INVTF612KTR', 'HB-PD_INVBW847XWJ', 'HB-PD_INVHX423RRQ', 'HB-PD_INVGG918HA8', 'HB-PD_INVKX795APD', 'HB-PD_INVZZ523BBG', 'HB-PD_INVME983PVW', 'HB-PD_INVPE171ERM', 'HB-PD_INVNL149VAN', 'HB-PD_INVPW750EM0', 'HB-PD_INVJM334XBX', 'HB-PD_INVVG233ZUC', 'HB-PD_INVBW207YCU', 'HB-PD_INVPA111ED3', 'HB-PD_INVAF194FCZ', 'HB-PD_INVTL881VVA', 'HB-PD_INVMY889XPG', 'HB-PD_INVDG728CYH', 'HB-PD_INVYJ017AHX', 'HB-PD_INVUB834JNH', 'HB-PD_INVCW700ZDZ', 'HB-PD_INVEA914BYC', 'HB-PD_INVGM167BLK', 'HB-PD_INVMH179FVX', 'HB-PD_INVPH737LZ0', 'HB-PD_INVME275NUC', 'HB-PD_INVJE733FPH', 'HB-PD_INVVD490MY8', 'HB-PD_INVBF956HZC', 'HB-PD_INVEP343XWP', 'HB-PD_INVXB431DEK', 'HB-PD_INVYR130NW0', 'HB-PD_INVXP571YY7', 'HB-PD_INVZH758MGX', 'HB-PD_INVPC958YGZ', 'HB-PD_INVKA923TL4', 'HB-PD_INVAK512XAM', 'HB-PD_INVNB363VHH', 'HB-PD_INVYD424DPZ', 'HB-PD_INVMF816TBV', 'HB-PD_INVKL811ZLY', 'HB-PD_INVNG645LUP', 'HB-PD_INVWH876BRL', 'HB-PD_INVAG118ZY3', 'HB-PD_INVBZ124FUG', 'HB-PD_INVDX373MWV', 'HB-PD_INVWC787PBU', 'HB-PD_INVXN576DBA', 'HB-PD_INVUV031HM9', 'HB-PD_INVPP704AZM', 'HB-PD_INVXW921GG8', 'HB-PD_INVEG988JY3', 'HB-PD_INVFZ299DJD', 'HB-PD_INVTY501LVC', 'HB-PD_INVHD416RHN', 'HB-PD_INVEF834PGU', 'HB-PD_INVZW010GB2', 'HB-PD_INVJA227TWW', 'HB-PD_INVLH496DDB', 'HB-PD_INVMJ225EDX', 'HB-PD_INVGL494EDD', 'HB-PD_INVWF044ZN0', 'HB-PD_INVKH002YBK', 'HB-PD_INVGA448ZC0', 'HB-PD_INVKY993PK8', 'HB-PD_INVYC255CTZ', 'HB-PD_INVKC407HM3', 'HB-PD_INVLE508AX4', 'HB-PD_INVXF070MYX', 'HB-PD_INVKU843MGU', 'HB-PD_INVWZ136RGQ', 'HB-PD_INVJP816BLF', 'HB-PD_INVWC787PBU', 'HB-PD_INVFY875JK3', 'HB-PD_INVRH572AT6', 'HB-PD_INVZJ012MP6', 'HB-PD_INVHE822LK3', 'HB-PD_INVNU270PWY', 'HB-PD_INVBN609PXB', 'HB-PD_INVJE275THF', 'HB-PD_INVFV309PGF', 'HB-PD_INVGP631BHZ', 'HB-PD_INVWB718ZEF', 'HB-PD_INVRB746NDP', 'HB-PD_INVYY563EUJ', 'HB-PD_INVGF308PTQ', 'HB-PD_INVDL524KG5', 'HB-PD_INVFR583YBQ', 'HB-PD_INVVB976YMT', 'HB-PD_INVXR827MPY', 'HB-PD_INVAE296YP8', 'HB-PD_INVEJ258NFN', 'HB-PD_INVNL149VAN', 'HB-PD_INVZW545BKJ', 'HB-PD_INVVX051CP7', 'HB-PD_INVMP221NA4', 'HB-PD_INVLR050HV9', 'HB-PD_INVXX218NV7', 'HB-PD_INVDL524KG5', 'HB-PD_INVLN063PU6', 'HB-PD_INVBX552PF8', 'HB-PD_INVFW182RFT', 'HB-PD_INVND200XBC', 'HB-PD_INVBE371MRZ', 'HB-PD_INVPR714RBJ', 'HB-PD_INVHX359JA4', 'HB-PD_INVLM077KED', 'HB-PD_INVKH838FRA', 'HB-PD_INVMP236ZNW', 'HB-PD_INVAF194FCZ', 'HB-PD_INVFZ601AVR', 'HB-PD_INVVB041NZ6', 'HB-PD_INVEH855RUB', 'HB-PD_INVDW976PL4', 'HB-PD_INVZL386RG3', 'HB-PD_INVVZ555EN2', 'HB-PD_INVCY121MD0', 'HB-PD_INVYC223MFK', 'HB-PD_INVYH256XZD', 'HB-PD_INVRJ007NAU', 'HB-PD_INVXB837HK7', 'HB-PD_INVYP127KH7', 'HB-PD_INVHU915HHP', 'HB-PD_INVHX788VYX', 'HB-PD_INVBZ124FUG', 'HB-PD_INVDB093UCA', 'HB-PD_INVVD894FDN', 'HB-PD_INVGK510ALQ', 'HB-PD_INVTD973GCE', 'HB-PD_INVGW890FG8', 'HB-PD_INVKR345UUJ', 'HB-PD_INVYD424DPZ', 'HB-PD_INVKL192GW7', 'HB-PD_INVHY628ZET', 'HB-PD_INVZL198WEA', 'HB-PD_INVZX194BGG', 'HB-PD_INVHV797UJJ', 'HB-PD_INVNP526LNX', 'HB-PD_INVVZ973LRV', 'HB-PD_INVCV174KCK', 'HB-PD_INVPG130CYJ', 'HB-PD_INVDF461GL0', 'HB-PD_INVFP955BLX', 'HB-PD_INVTE998TK0', 'HB-PD_INVDC903NK0', 'HB-PD_INVFY219ZUC', 'HB-PD_INVZL198WEA', 'HB-PD_INVNF460BB1', 'HB-PD_INVDK184UA1', 'HB-PD_INVPM571TLJ', 'HB-PD_INVRM901DKE', 'HB-PD_INVAP895JG3', 'HB-PD_INVVZ252WPJ', 'HB-PD_INVRE591WEJ', 'HB-PD_INVCL175JXQ', 'HB-PD_INVTF612KTR', 'HB-PD_INVER130MFT', 'HB-PD_INVAM881MYM', 'HB-PD_INVFW763FLM', 'HB-PD_INVND271TBW', 'HB-PD_INVBB508ETG', 'HB-PD_INVGG918HA8', 'HB-PD_INVCD515MVR', 'HB-PD_INVWJ529CVP', 'HB-PD_INVXW747AZ4', 'HB-PD_INVZB944UB4', 'HB-PD_INVZB944UB4', 'HB-PD_INVNG645LUP', 'HB-PD_INVZC874MMT', 'HB-PD_INVJP149XZ2', 'HB-PD_INVAX717MD3', 'HB-PD_INVDZ945TRA', 'HB-PD_INVKT966MN3', 'HB-PD_INVBT078TVX', 'HB-PD_INVXP347HF0', 'HB-PD_INVJK763PMP', 'HB-PD_INVMA354DW9', 'HB-PD_INVNX156YX5', 'HB-PD_INVKH002YBK', 'HB-PD_INVCX130BPY', 'HB-PD_INVHP541XD3', 'HB-PD_INVMW299KWB', 'HB-PD_INVMG411AZK', 'HB-PD_INVEJ662KV5', 'HB-PD_INVCU116FVB', 'HB-PD_INVAT016EHQ', 'HB-PD_INVJT536LM4', 'HB-PD_INVLM804UVT', 'HB-PD_INVVM621ATM', 'HB-PD_INVBE012XDN', 'HB-PD_INVEU686NEC', 'HB-PD_INVRU910TJM', 'HB-PD_INVEA790TMH', 'HB-PD_INVXD012XR2', 'HB-PD_INVRM901DKE', 'HB-PD_INVLZ949CU1', 'HB-PD_INVZF427YRB', 'HB-PD_INVFM928EJ0', 'HB-PD_INVHE063PPK', 'HB-PD_INVPY574GRT', 'HB-PD_INVRD245ZDR', 'HB-PD_INVZL094PJ9', 'HB-PD_INVRD245ZDR', 'HB-PD_INVUF254ME1', 'HB-PD_INVKH338LMV', 'HB-PD_INVRY308XG0', 'HB-PD_INVMR253WC7', 'HB-PD_INVBM272LTX', 'HB-PD_INVKJ120VLF', 'HB-PD_INVMD661BPN', 'HB-PD_INVBW974KA6', 'HB-PD_INVUJ512TJL', 'HB-PD_INVZV042MNW', 'HB-PD_INVHV797UJJ', 'HB-PD_INVBZ124FUG', 'HB-PD_INVCZ095RYE', 'HB-PD_INVBM610UB6', 'HB-PD_INVCX232RZZ', 'HB-PD_INVDT492THE', 'HB-PD_INVVU362RRK', 'HB-PD_INVRJ007NAU', 'HB-PD_INVLE508AX4', 'HB-PD_INVVU362RRK', 'HB-PD_INVTH110CRQ', 'HB-PD_INVFK553TXD', 'HB-PD_INVGG854VFB', 'HB-PD_INVMT827DYR', 'HB-PD_INVBZ259XBL', 'HB-PD_INVPG781HYV', 'HB-PD_INVTZ831VV2', 'HB-PD_INVDR834KT6', 'HB-PD_INVZW319HXF', 'HB-PD_INVKT210TKP', 'HB-PD_INVRV272VEY', 'HB-PD_INVUD383EXF', 'HB-PD_INVRR113RA3', 'HB-PD_INVPN172RF8', 'HB-PD_INVVH572YUG', 'HB-PD_INVYK689VP7', 'HB-PD_INVVT242JK8', 'HB-PD_INVGX160CCD', 'HB-PD_INVHH297BET', 'HB-PD_INVKN398WMH', 'HB-PD_INVXN576DBA', 'HB-PD_INVRE373FMT', 'HB-PD_INVJR322BC9', 'HB-PD_INVKC407HM3', 'HB-PD_INVLZ584HX7', 'HB-PD_INVUD383EXF', 'HB-PD_INVAD033HX2', 'HB-PD_INVPA111ED3', 'HB-PD_INVWF817ZDG', 'HB-PD_INVRF972FVE', 'HB-PD_INVGJ902ULN', 'HB-PD_INVMU467HLD', 'HB-PD_INVMW299KWB', 'HB-PD_INVRK101NLR', 'HB-PD_INVGF308PTQ', 'HB-PD_INVKR345UUJ', 'HB-PD_INVCD515MVR', 'HB-PD_INVGD528UUF', 'HB-PD_INVLR599UE9', 'HB-PD_INVZF030ANB', 'HB-PD_INVAX717MD3', 'HB-PD_INVDA056MAY', 'HB-PD_INVFR583YBQ', 'HB-PD_INVWK621GKJ', 'HB-PD_INVPH737LZ0', 'HB-PD_INVEK775PZ1', 'HB-PD_INVRP514MYT', 'HB-PD_INVLH496DDB', 'HB-PD_INVRE473WBY', 'HB-PD_INVJF352UPG', 'HB-PD_INVRU910TJM', 'HB-PD_INVNB271ZJA', 'HB-PD_INVLA508YEX', 'HB-PD_INVNJ300ULP', 'HB-PD_INVFA055PFA', 'HB-PD_INVWP517WBR', 'HB-PD_INVXR438DPG', 'HB-PD_INVTV257XUC', 'HB-PD_INVEY788YLQ', 'HB-PD_INVXW804UWZ', 'HB-PD_INVJR322BC9', 'HB-PD_INVFK806NX7', 'HB-PD_INVGP996TTC', 'HB-PD_INVAV534PAK', 'HB-PD_INVYW846EJE', 'HB-PD_INVJN333YR7', 'HB-PD_INVFZ299DJD', 'HB-PD_INVJJ715WZM', 'HB-PD_INVDZ226WHL', 'HB-PD_INVTA736CUG', 'HB-PD_INVXD556XFQ', 'HB-PD_INVGM472XLN', 'HB-PD_INVKH531VAT', 'HB-PD_INVLN081LWQ', 'HB-PD_INVKV807AMT', 'HB-PD_INVDP335EP6', 'HB-PD_INVFE029ZGM', 'HB-PD_INVVZ810CL4', 'HB-PD_INVBJ303BHF', 'HB-PD_INVAR135FG7', 'HB-PD_INVDV220XUE', 'HB-PD_INVRX901LF2', 'HB-PD_INVLH617NTN', 'HB-PD_INVPM571TLJ', 'HB-PD_INVFY875JK3', 'HB-PD_INVDH961RPQ', 'HB-PD_INVNL754MDA', 'HB-PD_INVRC954HCG', 'HB-PD_INVGK510ALQ', 'HB-PD_INVBA574HY3', 'HB-PD_INVMY698YC7', 'HB-PD_INVRP927JCT', 'HB-PD_INVFB371KHM', 'HB-PD_INVAK512XAM', 'HB-PD_INVZK380FLN', 'HB-PD_INVAC618MF7', 'HB-PD_INVZL094PJ9', 'HB-PD_INVED353HFW', 'HB-PD_INVUF871WH1', 'HB-PD_INVHD416RHN', 'HB-PD_INVBW847XWJ', 'HB-PD_INVDT841GGQ', 'HB-PD_INVTD267ZYJ', 'HB-PD_INVNP526LNX', 'HB-PD_INVLY369CT2', 'HB-PD_INVVG290KEJ', 'HB-PD_INVNF460BB1', 'HB-PD_INVMF782LD5', 'HB-PD_INVPR211RHG', 'HB-PD_INVUV592GPE', 'HB-PD_INVMA476BGX', 'HB-PD_INVUL126MB0', 'HB-PD_INVDA056MAY', 'HB-PD_INVZD105WP0', 'HB-PD_INVUY723HWK', 'HB-PD_INVEA688XUL', 'HB-PD_INVCF880VPM', 'HB-PD_INVZV637MJM', 'HB-PD_INVPG781HYV', 'HB-PD_INVKA923TL4', 'HB-PD_INVJL623KZJ', 'HB-PD_INVAF810DJL', 'HB-PD_INVAT813UH6', 'HB-PD_INVLZ584HX7', 'HB-PD_INVJE733FPH', 'HB-PD_INVZX194BGG', 'HB-PD_INVLA628ABM', 'HB-PD_INVEG988JY3', 'HB-PD_INVME058GGE', 'HB-PD_INVLR448GRG', 'HB-PD_INVGM472XLN', 'HB-PD_INVAJ778TMQ', 'HB-PD_INVGD551KWU', 'HB-PD_INVTV257XUC', 'HB-PD_INVWX362DL7', 'HB-PD_INVBM272LTX', 'HB-PD_INVJP816BLF', 'HB-PD_INVUT297BGD', 'HB-PD_INVZV637MJM', 'HB-PD_INVLB109TD3', 'HB-PD_INVLR448GRG', 'HB-PD_INVXA800WUB', 'HB-PD_INVWM581RNG', 'HB-PD_INVBE012XDN', 'HB-PD_INVCL175JXQ', 'HB-PD_INVDF461GL0', 'HB-PD_INVVT242JK8', 'HB-PD_INVHN432RJP', 'HB-PD_INVBX181DJ7', 'HB-PD_INVBX552PF8', 'HB-PD_INVZA054JF4', 'HB-PD_INVPF517DTL', 'HB-PD_INVZC389ZW4', 'HB-PD_INVXW592YL6', 'HB-PD_INVNJ509XCP', 'HB-PD_INVNA228DKV', 'HB-PD_INVBM272LTX', 'HB-PD_INVYJ928WUU', 'HB-PD_INVJD942HAQ', 'HB-PD_INVMT562GR7', 'HB-PD_INVNB271ZJA', 'HB-PD_INVNF545AYA', 'HB-PD_INVFA055PFA', 'HB-PD_INVAW340LT3', 'HB-PD_INVLW937KHT', 'HB-PD_INVVX846MNN', 'HB-PD_INVZC874MMT', 'HB-PD_INVYC223MFK', 'HB-PD_INVBE371MRZ', 'HB-PD_INVYE811LLA', 'HB-PD_INVRU892YEU', 'HB-PD_INVJK763PMP', 'HB-PD_INVWG508WXY', 'HB-PD_INVWD198FDP', 'HB-PD_INVLT278CV0', 'HB-PD_INVXM962ZLR', 'HB-PD_INVAC488AAF', 'HB-PD_INVAP895JG3', 'HB-PD_INVEF834PGU', 'HB-PD_INVJN233DCK', 'HB-PD_INVDP283FXX', 'HB-PD_INVRP448VZ3', 'HB-PD_INVFG174KZN', 'HB-PD_INVHB570DA9', 'HB-PD_INVXF759LZZ', 'HB-PD_INVUF871WH1', 'HB-PD_INVNU697YE1', 'HB-PD_INVMU467HLD', 'HB-PD_INVWG508WXY', 'HB-PD_INVXG139MTD', 'HB-PD_INVPF517DTL', 'HB-PD_INVAF323PK0', 'HB-PD_INVXD458VNK', 'HB-PD_INVRT078KR7', 'HB-PD_INVWC268DZQ', 'HB-PD_INVJZ026ZJQ', 'HB-PD_INVPP709FVL', 'HB-PD_INVCV174KCK', 'HB-PD_INVTH110CRQ', 'HB-PD_INVRR113RA3', 'HB-PD_INVTL881VVA', 'HB-PD_INVRT791CHG', 'HB-PD_INVVF912FXN', 'HB-PD_INVCR113DZ8', 'HB-PD_INVWF817ZDG', 'HB-PD_INVZW319HXF', 'HB-PD_INVAG118ZY3', 'HB-PD_INVDL524KG5', 'HB-PD_INVLG816FA8', 'HB-PD_INVNT332YE3', 'HB-PD_INVWD135LET', 'HB-PD_INVLK313WRF', 'HB-PD_INVXX218NV7', 'HB-PD_INVRV272VEY', 'HB-PD_INVUJ813CTX', 'HB-PD_INVXD751CUN', 'HB-PD_INVWU933JDG', 'HB-PD_INVYA191TPC', 'HB-PD_INVTL881VVA', 'HB-PD_INVZH758MGX', 'HB-PD_INVZX511PA8', 'HB-PD_INVEA688XUL', 'HB-PD_INVDW652EHZ', 'HB-PD_INVUF542CRR', 'HB-PD_INVWJ779MM6', 'HB-PD_INVJP149XZ2', 'HB-PD_INVJY190TER', 'HB-PD_INVNF545AYA', 'HB-PD_INVVF954NPT', 'HB-PD_INVBV727RB0', 'HB-PD_INVAT768TZD', 'HB-PD_INVUD896CCK', 'HB-PD_INVCP770RRH', 'HB-PD_INVLM804UVT', 'HB-PD_INVCZ382ZKF', 'HB-PD_INVHX359JA4', 'HB-PD_INVMC076TG1', 'HB-PD_INVAK293NGR', 'HB-PD_INVKJ264GGH', 'HB-PD_INVWD866VYY', 'HB-PD_INVLK313WRF', 'HB-PD_INVNJ762NBC', 'HB-PD_INVXJ077RRF', 'HB-PD_INVFP716LL3', 'HB-PD_INVXR075LL5', 'HB-PD_INVWB112CKF', 'HB-PD_INVEY788YLQ', 'HB-PD_INVFZ130YWL', 'HB-PD_INVLB109TD3', 'HB-PD_INVVD953YJZ', 'HB-PD_INVKB560VKQ', 'HB-PD_INVNY162MAJ', 'HB-PD_INVBE012XDN', 'HB-PD_INVAK776WJ1', 'HB-PD_INVVX051CP7', 'HB-PD_INVWH876BRL', 'HB-PD_INVXJ954YJ0', 'HB-PD_INVUC085LK0', 'HB-PD_INVZK469HAD', 'HB-PD_INVYF814FDZ', 'HB-PD_INVGZ856KJ7', 'HB-PD_INVWG304XLP', 'HB-PD_INVHU915HHP', 'HB-PD_INVJT019TG6', 'HB-PD_INVTP621WL7', 'HB-PD_INVVG026PAC', 'HB-PD_INVFB954CZL', 'HB-PD_INVTT996AAG', 'HB-PD_INVXG323UHM', 'HB-PD_

In [ ]:
# Filter metadata_df to keep only rows matching AMP PD df columns
filtered_metadata_df = PD_metadata[PD_metadata['participant_id'].isin(processed_strings)]
filtered_metadata_df = filtered_metadata_df.rename(columns={"participant_id": "sample_id", "case_control_other_at_baseline": "group"})
filtered_metadata_df

In [ ]:
# Create new metadata df for AMP CMD
import pandas as pd

samples = list(CMD_df.columns)

cmd_meta = pd.DataFrame({
    "sample_id": samples,
    "group": [
        np.nan if s.startswith("G") else  
        "Control" if "U" in s else 
        "Treatment" if "T" in s else 
        np.nan
        for s in samples
    ]
})
cmd_meta

In [ ]:
# Combine AMP CMD metadata
metadata1 = cmd_meta
metadata2 = filtered_metadata_df
metadata = pd.concat([metadata1, metadata2])

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Read merged counts and transpose
merged_counts = pd.read_csv(merged_counts, index_col=0) 
data_transposed = merged_counts.T

# z-score normalize the data
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_transposed)

# Fit PCA on the data and transform
pca = PCA(n_components=2)
pca_result = pca.fit_transform(data_scaled)

# Create PCA dataframe and merge with metadata
pca_df = pd.DataFrame(pca_result, columns=["PC1", "PC2"])
pca_df["Sample"] = data_transposed.index  # Add sample names
pca_df = pca_df.merge(metadata, on="Sample")

# Plot PCs
fig_pca = px.scatter(
    pca_df,
    x="PC1",
    y="PC2",
    color="Disease",
    hover_data=["Sample"],
    title="PCA of Merged Transcriptomics Data",
    labels={
        "PC1": f"PC1 ({pca.explained_variance_ratio_[0]*100:.2f}%)", 
        "PC2": f"PC2 ({pca.explained_variance_ratio_[1]*100:.2f}%)"
    },
    template="plotly_white"
)
fig_pca.show()

# Isolate the 50 most variable genes
top_genes = merged_counts.var(axis=1).nlargest(50).index
top_gene_counts = merged_counts.loc[top_genes]

# Plot a heatmap of the 50 most variable genes
plt.figure(figsize=(12, 8))
sns.heatmap(
    top_gene_counts, cmap="viridis",
    yticklabels=True, xticklabels=False
)
plt.title("Heatmap of Top 50 Most Variable Genes")
plt.xlabel("Samples")
plt.ylabel("Genes")
plt.show()

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.stats.multitest import multipletests

# Read in merged counts and metadata, set Sample column as the index
merged_counts = pd.read_csv("merged_counts.csv", index_col=0)  
metadata = pd.read_csv("metadata.csv")  
metadata = metadata.set_index("Sample")
merged_counts = merged_counts[metadata.index]  

# List unique diseases, throw an error if there are more than 2
unique_diseases = metadata["Disease"].unique()

if len(unique_diseases) != 2:
    raise ValueError("This script supports only two-group comparisons (e.g., Disease_A vs. Disease_B)")

# Label diseases and controls
case_label, control_label = unique_diseases
group_labels = (metadata["Disease"] == case_label).astype(int)  
log_counts = np.log2(merged_counts + 1)  

# Initialize lists to store values
p_values, logFC_values, beta_intercepts = [], [], []

X = sm.add_constant(group_labels.values)

# Loop through genes to get appropriate stats
for gene in log_counts.index:
    y = log_counts.loc[gene, :]
    model = sm.OLS(y, X).fit()
    
    beta_intercepts.append(model.params[0])  
    logFC_values.append(model.params[1]) 
    p_values.append(model.pvalues[1]) 

# Adjust p-values using multiple test correction
adj_p_values = multipletests(p_values, method="fdr_bh")[1]

# Build new dataframe from the lists
results_df = pd.DataFrame({
    "Gene": log_counts.index,
    "Beta_Intercept (β0)": beta_intercepts,
    "Beta_Case (β1)": logFC_values,  # logFC (effect size)
    "P_Value": p_values,
    "Adj_P_Value": adj_p_values
})

# Filter significant DEGs (FDR < 0.05)
significant_degs = results_df[results_df["Adj_P_Value"] < 0.05]

In [ ]:
import pandas as pd

# Sample metadata dataframe (Assuming it's loaded from a CSV or DataFrame)
sample_meta = pd.read_csv("sample_metadata.csv")  # Uncomment if reading from a CSV

# Filter Case samples based on study and visit
sample_case = sample_meta[
    (sample_meta["study"].isin(setStudy)) &
    (sample_meta["visit_month"].isin(setMonth)) &
    (sample_meta["case_control_other_at_baseline"] == "Case")
]
print(sample_case.shape)  # (1370, 63)


# Filter Control samples based on study and visit
sample_control = sample_meta[
    (sample_meta["study"].isin(setStudy)) &
    (sample_meta["visit_month"].isin(setMonth)) &
    (sample_meta["case_control_other_at_baseline"] == "Control")
]
print(sample_control.shape)  # (954, 63)


# Combine Case and Control tables
sample_meta = pd.concat([sample_case, sample_control], ignore_index=True)
print(sample_meta.shape)  # (2324, 63)

# Summary of the Cohort
print("How many unique sample IDs do we have?")
print(sample_meta["sample_id"].nunique())

print("Which studies are these sample IDs from?")
print(sample_meta["study"].value_counts())

print("How many case and control samples are there at baseline?")
print(sample_meta["case_control_other_at_baseline"].value_counts())

print("How many case and control samples are there at the latest visit? Is there a change between baseline and latest?")
print(sample_meta["case_control_other_latest"].value_counts())

print("How many samples have known LRRK2 mutations?")
print(sample_meta["has_known_LRRK2_mutation_in_WGS"].value_counts())

print("What are the dimensions of the final, merged sample table")
print(sample_meta.shape)

print("Show headers of the sample table")
print(sample_meta.head())

# Save the final merged table
sample_meta.to_csv("filtered_sample_meta.csv", index=False)